### ISSUE TITLE
Issue in doc

### ISSUE THREAD

**Issue by thesteve0** [CrunchyData/crunchy-pg#2]
In https://github.com/CrunchyData/crunchy-pg/blob/master/docs/openshift-setup-nodes.md

I don't understand what the line 

Test this out by entering the following when logged into openshift:

id

means. What does it mean to be logged into OpenShift? Do you mean oc exec into a pod?

**Comment by jmccormick2001** [comment]
see if the updated document is worded better.  I meant to exec into the pod and then issue the 'id' command.
